import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  
  subsets: ["latin"],
});

export const metadata = {
  title: "NERO PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= 
      {`${geistSans.variable} ${geistMono.variable}
       className='h-full min-h-screen
    bg-[url("/dark.jpg")]
      bg-cover bg-center bg-fixed '`}>
        {children}
      </body>
    </html>
  );
}
