import Head from 'next/head';

import Navbar from "./components/Navbar";
import Hero from './components/Hero';
import About from './components/About';
import Skills from './components/Skills';
import Projects from './components/Projects';
import Contact from './components/Contact';


export default function Home() {
  return (
    <div
      className='h-full min-h-screen
      bg-black
      bg-cover bg-center bg-fixed relative  scroll-smooth'>
      <div className="absolute inset-0 bg-black opacity-10"></div>
      <Head>
        <title>Nero portfolio</title>
        <meta name="description " content ="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <header className="relative z-10">
        <Navbar/>
      </header>
      <main className="relative z-20">
        <div className=''>
          <Hero/>
          <About/>
          <Projects/>
          <Skills/>
          <Contact/>
        </div>
      </main>
    </div>
  );
}
